
networks:
  default:

services:
  db:
    image: mysql:5.7
    container_name: conference
    ports:
    - 3306:3306
    volumes:
    - C:\Workspace\mysql\data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: conference